// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/BaliRetreatExpenseTracker-aaR-LB/App.tsx": () => import("../components/mockups/templates/BaliRetreatExpenseTracker-aaR-LB/App.tsx"),
  "./components/mockups/templates/ModernBankingDashboard-QJx8fA/VaultBanking.tsx": () => import("../components/mockups/templates/ModernBankingDashboard-QJx8fA/VaultBanking.tsx")
};
